version: 2

sources:
  - name: raw
    database: sales_forecasting
    schema: raw
    tables:
      - name: stg_key
      - name: stg_sales
      - name: stg_weather
      - name: stg_holidays
      - name: stg_blackfriday