name: 'sales_forecasting_lakehouse'
version: '1.0.0'
profile: 'sales_forecasting_lakehouse'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sales_forecasting_lakehouse:
    staging:
      +materialized: view
      +schema: default
    intermediate:
      +materialized: view
      +schema: default
    marts:
      +materialized: table
      +file_format: iceberg
