stages:
  prepare_data:
    cmd: cd ../ml && uv run python -m scripts.prepare_data
    deps:
      - ../ml/scripts/prepare_data.py
      - data/data_raw/test.csv
    params:
      - prepare.cutoff_date
    outs:
      - data/processed/train.parquet
      - data/processed/valid.parquet
      - data/processed/test.parquet

  train:
    cmd: >
      cd ../ml && uv run python -m scripts.train
      --train-path ../shared/data/processed/train.parquet
      --valid-path ../shared/data/processed/valid.parquet
      --model-out ../shared/models/lgbm_baseline.pkl
      --metrics-out ../shared/outputs/metrics.json
    deps:
      - ../ml/scripts/train.py
      - ../ml/processing/validator.py
      - data/processed/train.parquet
      - data/processed/valid.parquet
    params:
      - train
    outs:
      - models/lgbm_baseline.pkl
    metrics:
      - outputs/metrics.json:
          cache: false

  tune:
    cmd: >
      cd ../ml && uv run python -m scripts.tune
      --train-path ../shared/data/processed/train.parquet
      --valid-path ../shared/data/processed/valid.parquet
      --out-best-params ../shared/outputs/tuning/best_params.json
    deps:
      - ../ml/scripts/tune.py
      - ../ml/tuning/objective.py
      - data/processed/train.parquet
      - data/processed/valid.parquet
    params:
      - tune
    outs:
      - outputs/tuning/best_params.json
