spark.master                                    spark://spark-master:7077
spark.hadoop.fs.s3a.endpoint                    http://minio:9000
spark.hadoop.fs.s3a.path.style.access           true
spark.hadoop.fs.s3a.connection.ssl.enabled      false
spark.hadoop.fs.s3a.access.key                  minioadmin
spark.hadoop.fs.s3a.secret.key                  minioadmin
spark.hadoop.fs.s3a.aws.credentials.provider    org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.impl                        org.apache.hadoop.fs.s3a.S3AFileSystem
spark.ui.showConsoleProgress                    false
spark.pyspark.python                            /usr/bin/python3.12
spark.pyspark.driver.python                     python3
spark.executor.cores                            1
spark.executor.memory                           512m
spark.executor.memoryOverhead                   256m
spark.driver.memory                             1g
spark.driver.port                               7078
spark.blockManager.port                         7079

