spark.master                                    spark://spark-master:7077
spark.ui.showConsoleProgress                    false
spark.pyspark.python                            /usr/bin/python3.12
spark.pyspark.driver.python                     python3
spark.executor.cores                            1
spark.executor.memory                           512m
spark.executor.memoryOverhead                   256m
spark.driver.memory                             1g
spark.driver.port                               7078
spark.blockManager.port                         7079

# Iceberg & Nessie Extensions
spark.sql.extensions                            org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

# Nessie Catalog
spark.sql.catalog.nessie                        org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.nessie.catalog-impl           org.apache.iceberg.nessie.NessieCatalog
spark.sql.catalog.nessie.uri                    http://nessie:19120/api/v1
spark.sql.catalog.nessie.ref                    main
spark.sql.catalog.nessie.authentication.type    NONE
spark.sql.catalog.nessie.warehouse              s3://datalake/iceberg/
spark.sql.catalog.nessie.s3.endpoint            http://minio:9000
spark.sql.catalog.nessie.s3.path-style-access   true
spark.sql.defaultCatalog                        nessie

# Using HadoopFileIO (Default) with s3:// -> s3a:// mapping below

# Mapping s3:// to S3A implementation
# This allows Spark to process s3:// URIs using the S3A library
spark.hadoop.fs.s3.impl                                  org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint                              http://minio:9000
spark.hadoop.fs.s3a.path.style.access                    true
spark.hadoop.fs.s3a.connection.ssl.enabled               false
spark.hadoop.fs.s3a.access.key                           minioadmin
spark.hadoop.fs.s3a.secret.key                           minioadmin
spark.hadoop.fs.s3a.impl                                 org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider             org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider



